Feature 005.1.1 002
KOH6/hc_practice pull request #2
Opened 2023-07-09 04:34 UTC by KOH6

@ihatov08 
以下課題のプルリクエストです。ご確認よろしくお願いいたします。

## 課題のリンク
* [005.1.1_html_css/002_アウトプット課題.md](https://github.com/happiness-chain/practice/blob/main/005.1.1_html_css/002_%E3%82%A2%E3%82%A6%E3%83%88%E3%83%97%E3%83%83%E3%83%88%E8%AA%B2%E9%A1%8C.md)

## やったこと
* zenn.dev の記事詳細ページの模写を作成しました。

## 動作確認方法
* Github Pagesで模写ページを公開しておりますのでご確認よろしくお願いいたします。
  * https://koh6.github.io/hc_practice/index.html

## その他
* ブレイクポイントは以下で作成しました。
  * モバイル：設定なし
  * 小さめのタブレット：768px~
  * タブレット：820px~
  * PC：1024px~

2023-07-09 13:07 UTC, ihatov08 approved these changes
[Video_2023_07_09-1.webm](https://github.com/KOH6/hc_practice/assets/14024165/760f295d-57e2-4453-8f67-771641db9d20)

確認しました、結構本家とことなるので修正お願いします 🙇

2023-07-09 13:08 UTC, ihatov08 requested changes
修正お願いします！

2023-07-10 13:40 UTC, KOH6 commented
@ihatov08 
修正を加えました。再度ご確認をお願いいたします！

## 修正内容
* 1280px以上のPCサイズのレスポンシブ対応を追加しました。
* レスポンシブ対応のブレイクポイントを増やしたことによる微調整を行いました。

2023-07-11 01:13 UTC, ihatov08 approved these changes
確認しました、LGTMです！

ps
pull requestのtitleは一目でわかるような名前を次回からつけましょう！

2023-07-11 10:53 UTC, KOH6 commented
@ihatov08 
ご確認ありがとうございました！
タイトルについては大変失礼いたしました。
プルリクエストのタイトルを「コーディング模写課題対応」に変更いたしました。

マージいたします！

2023-07-11 10:55 UTC, merged